global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: go_.*
      action: drop
    - source_labels: [__name__]
      regex: process_.*
      action: drop

