name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Python Pylin GitHub Action
        uses: fylein/python-pytest-github-action@v1
        with:
          args: python setup.py install && pytest
